name: coverage
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: '3.11' 
        
    - name: Install coverage
      run: python -m pip install coverage
    
    - name: Install pytest
      run: python -m pip install pytest
      
    - name: Install click
      run: python -m pip install click

    - name: Test coverage
      run: |
        python -m coverage run -m pytest tests
        coverage_percentage=$(coverage report | awk 'END {print $4}')
        echo "COVERAGE_PERCENTAGE=$coverage_percentage" >> $GITHUB_ENV
      shell: bash

    - name: Generate coverage report
      run: coverage html -d coverage_report
      continue-on-error: true

    - name: Set Coverage Percentage 
      id: set_coverage
      run: echo "COVERAGE_PERCENTAGE=${{ steps.build.outputs.coverage_percentage }}" >> $GITHUB_ENV

  coverage_badge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.3

    - name: Create coverage badge
      run: |
        coverage_percentage=${{ env.COVERAGE_PERCENTAGE }}
        if [[ $coverage_percentage == "100%" ]]; then
          badge_message="coverage-100%25-brightgreen"
        else
          badge_message="coverage-$coverage_percentage-yellow"
        fi
        echo "[![coverage](https://img.shields.io/badge/$badge_message)](https://github.com/kradt/aioskd/actions/workflows/ci_coverage.yml)" >> README.md
      shell: bash