name: coverage
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.2

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: '3.11' 
        
    - name: Install coverage
      run: python -m pip install coverage

    - name: Install pytest-async
      run: python -m pip install pytest-asyncio
    
    - name: Install pytest
      run: python -m pip install pytest
      
    - name: Install click
      run: python -m pip install click

    - name: Test coverage
      run: python -m coverage run --source=aioskd -m pytest tests

      shell: bash

    - name: Generate coverage report
      run: coverage html -d coverage_report
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3 